# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 686)
        MainWindow.setMinimumSize(QtCore.QSize(800, 0))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 5, 1, 1)
        self.serialPort_label = QtWidgets.QLabel(self.centralwidget)
        self.serialPort_label.setObjectName("serialPort_label")
        self.gridLayout.addWidget(self.serialPort_label, 2, 0, 1, 1)
        self.rtscts = QtWidgets.QCheckBox(self.centralwidget)
        self.rtscts.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.rtscts.setChecked(True)
        self.rtscts.setObjectName("rtscts")
        self.gridLayout.addWidget(self.rtscts, 3, 2, 1, 1)
        self.baudrare_label = QtWidgets.QLabel(self.centralwidget)
        self.baudrare_label.setObjectName("baudrare_label")
        self.gridLayout.addWidget(self.baudrare_label, 3, 0, 1, 1)
        self.stopBits = QtWidgets.QComboBox(self.centralwidget)
        self.stopBits.setObjectName("stopBits")
        self.stopBits.addItem("")
        self.stopBits.addItem("")
        self.stopBits.addItem("")
        self.gridLayout.addWidget(self.stopBits, 6, 1, 1, 1)
        self.stopBits_label = QtWidgets.QLabel(self.centralwidget)
        self.stopBits_label.setObjectName("stopBits_label")
        self.gridLayout.addWidget(self.stopBits_label, 6, 0, 1, 1)
        self.dsrdtr = QtWidgets.QCheckBox(self.centralwidget)
        self.dsrdtr.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.dsrdtr.setChecked(True)
        self.dsrdtr.setObjectName("dsrdtr")
        self.gridLayout.addWidget(self.dsrdtr, 4, 2, 1, 1)
        self.byteSize_label = QtWidgets.QLabel(self.centralwidget)
        self.byteSize_label.setObjectName("byteSize_label")
        self.gridLayout.addWidget(self.byteSize_label, 4, 0, 1, 1)
        self.xonxoff = QtWidgets.QCheckBox(self.centralwidget)
        self.xonxoff.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.xonxoff.setObjectName("xonxoff")
        self.gridLayout.addWidget(self.xonxoff, 2, 2, 1, 1)
        self.serialPort = QtWidgets.QLineEdit(self.centralwidget)
        self.serialPort.setBaseSize(QtCore.QSize(0, 0))
        self.serialPort.setObjectName("serialPort")
        self.gridLayout.addWidget(self.serialPort, 2, 1, 1, 1)
        self.baudRate = QtWidgets.QLineEdit(self.centralwidget)
        self.baudRate.setObjectName("baudRate")
        self.gridLayout.addWidget(self.baudRate, 3, 1, 1, 1)
        self.parity_label = QtWidgets.QLabel(self.centralwidget)
        self.parity_label.setObjectName("parity_label")
        self.gridLayout.addWidget(self.parity_label, 5, 0, 1, 1)
        self.byteSize = QtWidgets.QComboBox(self.centralwidget)
        self.byteSize.setEditable(False)
        self.byteSize.setFrame(True)
        self.byteSize.setObjectName("byteSize")
        self.byteSize.addItem("")
        self.byteSize.addItem("")
        self.byteSize.addItem("")
        self.byteSize.addItem("")
        self.gridLayout.addWidget(self.byteSize, 4, 1, 1, 1)
        self.parity = QtWidgets.QComboBox(self.centralwidget)
        self.parity.setObjectName("parity")
        self.parity.addItem("")
        self.parity.addItem("")
        self.parity.addItem("")
        self.parity.addItem("")
        self.parity.addItem("")
        self.gridLayout.addWidget(self.parity, 5, 1, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 6)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 6)
        self.disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.disconnect.setObjectName("disconnect")
        self.gridLayout.addWidget(self.disconnect, 6, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 3, 1, 1)
        self.connect = QtWidgets.QPushButton(self.centralwidget)
        self.connect.setObjectName("connect")
        self.gridLayout.addWidget(self.connect, 6, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setEnabled(True)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.byteSize.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.serialPort_label.setText(_translate("MainWindow", "Serial Port"))
        self.rtscts.setText(_translate("MainWindow", "rtscts"))
        self.baudrare_label.setText(_translate("MainWindow", "Baudrate"))
        self.stopBits.setItemText(0, _translate("MainWindow", "serial.STOPBITS_ONE"))
        self.stopBits.setItemText(1, _translate("MainWindow", "serial.STOPBITS_ONE_POINT_FIVE"))
        self.stopBits.setItemText(2, _translate("MainWindow", "serial.STOPBITS_TWO"))
        self.stopBits_label.setText(_translate("MainWindow", "Stop Bits"))
        self.dsrdtr.setText(_translate("MainWindow", "dsrdtr"))
        self.byteSize_label.setText(_translate("MainWindow", "Byte Size"))
        self.xonxoff.setText(_translate("MainWindow", "xon xoff"))
        self.serialPort.setText(_translate("MainWindow", "COM3"))
        self.baudRate.setText(_translate("MainWindow", "9600"))
        self.parity_label.setText(_translate("MainWindow", "Parity"))
        self.byteSize.setItemText(0, _translate("MainWindow", "serial.FIVEBITS"))
        self.byteSize.setItemText(1, _translate("MainWindow", "serial.SIXBITS"))
        self.byteSize.setItemText(2, _translate("MainWindow", "serial.SEVENBITS"))
        self.byteSize.setItemText(3, _translate("MainWindow", "serial.EIGHTBITS"))
        self.parity.setItemText(0, _translate("MainWindow", "serial.PARITY_NONE"))
        self.parity.setItemText(1, _translate("MainWindow", "serial.PARITY_EVEN"))
        self.parity.setItemText(2, _translate("MainWindow", "serial.PARITY_ODD"))
        self.parity.setItemText(3, _translate("MainWindow", "serial.PARITY_MARK"))
        self.parity.setItemText(4, _translate("MainWindow", "serial.PARITY_SPACE"))
        self.disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.connect.setText(_translate("MainWindow", "Connect"))

